In [33]:
import pandas as pd
import numpy as np

# Load everything
df_albin = pd.read_csv(
    "../data/raw/albini2017.csv",
    parse_dates=["Date"],
    infer_datetime_format=True,
    dtype={
        "Likes": np.int32,
        "Comments": np.int32,
        "Shares": np.int32,
    },
)
df_vjosa = pd.read_csv(
    "../data/raw/VjosaOsmaniMP.csv",
    parse_dates=["Date"],
    infer_datetime_format=True,
    dtype={
        "Likes": np.int32,
        "Comments": np.int32,
        "Shares": np.int32,
    },
)
df_kadri = pd.read_csv(
    "../data/raw/kadriveseliofficial.csv",
    parse_dates=["Date"],
    infer_datetime_format=True,
    dtype={
        "Likes": np.float64,
        "Comments": np.int32,
        "Shares": np.int32,
    },
)
df_ramush = pd.read_csv(
    "../data/raw/RamushHaradinajOfficial.csv",
    parse_dates=["Date"],
    infer_datetime_format=True,
    dtype={
        "Likes": np.int32,
        "Comments": np.int32,
        "Shares": np.int32,
    },
)
df_fatmir = pd.read_csv(
    "../data/raw/FatmirLimajKM.csv",
    parse_dates=["Date"],
    infer_datetime_format=True,
    dtype={
        "Likes": np.int32,
        "Comments": np.int32,
        "Shares": np.int32,
    },
)

In [34]:
df_albin["Name"] = "Albin Kurti"
df_ramush["Name"] = "Ramush Haradinaj"
df_fatmir["Name"] = "Fatmir Limaj"
df_vjosa["Name"] = "Vjosa R. Osmani"
df_kadri["Name"] = "Kadri Veseli"

In [52]:
df_fatmir_daily = df_fatmir.groupby(df_fatmir["Date"].dt.date)["Likes", "Shares", "Comments"].sum()
df_fatmir_daily["Posts"] = df_fatmir.groupby(df_fatmir["Date"].dt.date)["Date"].count()
df_fatmir_daily["Name"] = "Fatmir Limaj"

In [53]:
df_fatmir_daily

            Likes  Shares  Comments  Posts          Name
Date
2019-04-09    140      96         1      1  Fatmir Limaj
2019-05-09    460      18         3      3  Fatmir Limaj
2019-06-09     54      13         0      1  Fatmir Limaj
2019-07-09    878      82        14      7  Fatmir Limaj
2019-08-28     90      95         4      1  Fatmir Limaj
2019-08-29    137     101         1      2  Fatmir Limaj